sync with upstream

diff --git a/linux-ck/PKGBUILD b/linux-ck/PKGBUILD
--- a/linux-ck/PKGBUILD
+++ b/linux-ck/PKGBUILD
@@ -57,9 +57,7 @@ _NUMAdisable=
 # that you currently have probed in your system VASTLY reducing the number of
 # modules built and the build time to do it.
 #
-# WARNING - ALL modules must be probed or loaded via a config file BEFORE you
-# begin making the pkg unless you're running modprobed-db (AUR) and building
-# this with makepkg as the user who is keeping the database.
+# WARNING - ALL modules must be probed BEFORE you begin making the pkg!
 #
 # To keep track of which modules are needed for your specific system/hardware,
 # give module_db script a try: https://aur.archlinux.org/packages/modprobed-db
@@ -71,7 +69,7 @@ _localmodcfg=
 ### IMPORTANT: Do no edit below this line unless you know what you're doing
 
 pkgbase=linux-ck
-_srcver=4.19.5-arch1
+_srcver=4.19.6-arch1
 pkgver=${_srcver%-*}
 pkgrel=1
 _ckpatchversion=1
@@ -96,7 +94,7 @@ validpgpkeys=(
   'ABAF11C65A2970B130ABE3C479BE3E4300411886'  # Linus Torvalds
   '647F28654894E3BD457199BE38DBBDC86092693E'  # Greg Kroah-Hartman
 )
-sha256sums=('8c839ec29cce7eb0e8ef7eaa10d1eb9d84d2be2521e352fb4f9414e76856ef75'
+sha256sums=('644e61beb66211c0c5c13f91d96de1725055e6eea4cda7bb37ce9929ba8f09c3'
             'SKIP'
             'f98f8c85afe172403f606e0d29d9c341c22e18d69939c3b58e8d7dca0f987bb5'
             'ae2e95db94ef7176207c690224169594d49445e04249d2499e9d2fbc117a0b21'
@@ -163,11 +161,12 @@ prepare() {
   ### Optionally load needed modules for the make localmodconfig
   # See https://aur.archlinux.org/packages/modprobed-db
     if [ -n "$_localmodcfg" ]; then
-      if [ -f $HOME/.config/modprobed.db ]; then
-        msg "Found a modprobed-db database for Steven Rostedt's make localmodconfig"
-        make LSMOD=$HOME/.config/modprobed.db localmodconfig
-      else
-        msg "Running Steven Rostedt's make localmodconfig now"
+      msg "If you have modprobed-db installed, running it in recall mode now"
+      if [ -e /usr/bin/modprobed-db ]; then
+        [[ -x /usr/bin/sudo ]] || {
+        echo "Cannot call modprobe with sudo. Install sudo and configure it to work with this user."
+        exit 1; }
+        sudo /usr/bin/modprobed-db recall
         make localmodconfig
       fi
     fi
